### PR TITLE
[quickfix] support big endian machines

### LINKED ISSUE #8: Doesn't work on big endian hosts
Hi @devongovett 
Linebreak works on big endian machines only if classes.trie is generated on big endian machine too. Otherwise there is an error
```
reak/src/linebreaker.js:122

switch (pairTable[this.curClass][this.nextClass]) {

^

TypeError: Cannot read property 'undefined' of undefined
```
Seen by @lcurcio at "IBM I" POWER system and by me on Debian MIPS

### PR DESCRIPTION
**Pull request by ghost**
Closes https://github.com/devongovett/linebreak/issues/8
Unless you're going to properly fix `unicode-trie`
cc @lcurcio

### CODE REVIEW

**Comment by KerimG** [comment]
Yes, please.

**Comment by KerimG** [comment]
Any update on this? The fix seems rather trivial, can it be merged?

@gnidorah how did you actually figure this out and how did you generate classes.trie.be? DId you have a big endian machine lying around?

**Comment by ghost** [comment]
> how did you generate classes.trie.be? 

via src/generate_data.coffee in this repository

> DId you have a big endian machine lying around?

Only qemu mips virtual machine

**Comment by KerimG** [comment]
@gnidorah but how did you find out it was the endianness, mate? I'm fascinated and I _must_ know!

**Comment by ghost** [comment]
@KerimG 
@lcurcio raised issue that linebreak doesn't work, in his logs I've seen that he uses "IBM I" POWER system which runs BE. So I though its related and tested in BE VM where I got the same issue. Then looking around I've seen the classes.trie.be blob, regenerating of which fixed the issue in VM.

**Comment by liborm85** [comment]
Will be fixed in https://github.com/foliojs/unicode-trie/pull/5.

**Pull request closed without merging**
