### PR TITLE
Build with Parcel

### LINKED ISSUE #5: Can't resolve 'fs'    ERROR in ./~/linebreak/src/linebreaker.js
Module not found: Error: Can't resolve 'fs' in  node_modules/linebreak/src'
 @ ./~/linebreak/src/linebreaker.js 7:7-20
 @ ./~/react-canvas/lib/measureText.js
 @ ./~/react-canvas/lib/ReactCanvas.js

### PR DESCRIPTION
**Pull request by devongovett**
Fixes #5, closes #6, closes #18.

In an effort to reduce build complexity while solving issues with browser builds, I'd like to use Parcel to build linebreak. Parcel will handle the `fs` inlining automatically. It will generate both CJS and ESM versions, compile with Babel for old browsers, etc. No custom build scripts needed.

This is dependent on a couple improvements to Parcel which will be going out shortly. Specifically https://github.com/parcel-bundler/parcel/pull/3800.

### CODE REVIEW

**Comment by blikblum** [comment]
Some notes:

 - The produced code has a lot of mangled variable names like `$fd07168cad7f4706624199b4e5e9fd36$export$NS` making the code basically unreadable. 
- The module build is broken (no LineBreaker class at all)

**Comment by devongovett** [comment]
> The produced code has a lot of mangled variable names

Yeah but it’s compiled so not really expecting people to read it.

> The module build is broken

Yup, see Parcel PR.

**Comment by blikblum** [comment]
> Yeah but it’s compiled so not really expecting people to read it.

When debugging (and in callstack traces) is important to get a readable code. Even minified code is better to debug due to source map.

Anyway, in the mean time parcel is improved, it can merge #18, so the libraries that depend of it can have a browser friendly build

**Comment by adroitwhiz** [comment]
Have the Parcel improvements landed?

**Comment by sibnerian** [comment]
Seems like the parcel changes have landed! Is anything blocking this? It would be great to have a browser-friendly build!

**Comment by zernie** [comment]
@devongovett @liborm85  sorry, could you please take a look at this PR?

**Pull request merged**
